spring:
  datasource:
    url: jdbc:postgresql://${WDFN_DATABASE_ADDRESS}:${WDFN_DATABASE_PORT}/${WDFN_DATABASE_NAME}
    username: ${WDFN_DB_READ_ONLY_USERNAME}
    password: ${WDFN_DB_READ_ONLY_PASSWORD}

logging:
  level:
    root: ${ROOT_LOG_LEVEL}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

site:
  url:
    base: ${SITE_URL_BASE:/}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
          - info
          - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never

collections:
  monitoring-locations:
    title: NWIS Monitoring Locations
    description: USGS water monitoring locations managed in the National Water Information System
    contactName: ${MONLOC_CONTACT_NAME:Internet of Water Product Owners}
    contactEmail: ${MONLOC_CONTACT_EMAIL:GS-W-iow_product_owners@usgs.gov}
